development:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: hu_api_development
  username: root
  password:

test:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: hu_api_test
  username: root
  password:

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: hu_api_production
  username: <%= ENV['HU_API_DB_USERNAME_PRODUCTION'] %>
  password: <%= ENV['HU_API_DB_PASSWORD_PRODUCTION'] %>