development:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: hu_api_development
  username: <%= ENV['MYSQL_ROOT_USERNAME'] %>
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>

test:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: hu_api_test
  username: <%= ENV['MYSQL_ROOT_USERNAME'] %>
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: hu_api_production
  username: <%= ENV['HU_API_DB_USERNAME_PRODUCTION'] %>
  password: <%= ENV['HU_API_DB_PASSWORD_PRODUCTION'] %>
