source 'https://rubygems.org'


gem 'rails', '4.2.4'
gem 'rails-api'
gem 'puma'
gem 'jbuilder'
gem 'mysql2'
gem 'rack-cors', :require => 'rack/cors'

group :development, :test do
  gem 'factory_girl'
  gem 'rspec-rails'
  gem 'byebug'
end

group :development do
 gem 'spring'
 gem 'rubocop'
end	

# Deploy with Capistrano
# gem 'capistrano', :group => :development
