source 'https://rubygems.org'


gem 'rails', '4.2.4'
gem 'rails-api'
gem 'puma'
gem 'jbuilder'
gem 'mysql2'
gem 'rack-cors', :require => 'rack/cors'
gem 'thor'
gem 'has_scope'
gem 'kaminari'
gem 'responders'
gem 'activerecord-import'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
end

group :test do
 gem 'factory_girl_rails'	

end

group :development do
 gem 'spring'
 gem 'rubocop'
end	

# Deploy with Capistrano
# gem 'capistrano', :group => :development
